
  CREATE TABLE "TJOEUNIT"."AACREGISTER" 
   (	"USERID" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"USERPASSWORD" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"USERNAME" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"USERAGE" NUMBER(*,0) NOT NULL ENABLE, 
	"USERGENDER" CHAR(6 BYTE) NOT NULL ENABLE, 
	"USEREMAIL" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "AACREGISTER_PK" PRIMARY KEY ("USERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

DELETE FROM aacregister;
DROP SEQUENCE aacregister_idx_seq;
CREATE SEQUENCE aacregister_idx_seq;


COMMIT;


select * from aacregister;